In [17]:
import numpy as np

In [18]:
values = ([1,2],[3,4],[5,6])
print("Training without Bias\n", values)

Training without Bias
 ([1, 2], [3, 4], [5, 6])


In [19]:
#Adding Bias 
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training with bias\n",values)

Training with bias
 [[-1  1  2]
 [-1  3  4]
 [-1  5  6]]


In [20]:
m=3  
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)

Initial random weights
 [[-0.40117045]
 [-0.44056111]
 [-0.41731295]]


In [21]:
#Target values Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)

Training data target values are
 ([0], [1], [1])


In [22]:
#updating weights
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights

In [23]:
# Learning

def  prediction (inputs, weights, targets):
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights

In [24]:
#Training 
iterations = 5
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)



Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Iteration  5 

[1]
[1]
[1]

Trained Weights
 [[0.09882955]
 [0.55943889]
 [0.08268705]]


In [25]:
#Testing 
def perceptronPredict(weights, newInput):
    ac = np.dot(newInput, weights)
    ac = np.where(ac>0, 1, 0)
    print(ac)


newInput = ([-1.0, 8, 9])
perceptronPredict(weights, newInput)

[1]
